catalog/urls.py
from django.urls import path

from catalog.apps import CatalogConfig
from catalog.views import home, contacts, CategoryListView, SneakersListView, SneakersCreateView, SneakersUpdateView

app_name = CatalogConfig.name

urlpatterns = [
    path('', home, name='home'),
    path('contacts/', contacts, name='contacts'),
    path('categories/', CategoryListView.as_view(), name='categories'),
    path('sneakers/', SneakersListView.as_view(), name='sneakers'),
    path('sneakers/create', SneakersCreateView.as_view(), name='sneakers_create'),
    path('sneakers/update/<int:pk>', SneakersUpdateView.as_view(), name='update_sneakers'),
]

online_store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models


NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    objects = None
    name = models.CharField(max_length=100, verbose_name='Имя')
    description = models.TextField(verbose_name='Описание', **NULLABLE)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Sneakers(models.Model):
    name = models.CharField(max_length=100, verbose_name='Имя')
    description = models.TextField(verbose_name='Описание', **NULLABLE)
    photo = models.ImageField(upload_to='sneakers/', verbose_name='Превью', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.IntegerField(verbose_name='Цена')
    date_make = models.DateField(verbose_name='Дата создания')
    date_update = models.DateField(verbose_name='Дата изменения')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Кроссовки'
        verbose_name_plural = 'Кроссовки'


class Blouses(models.Model):
    name = models.CharField(max_length=100, verbose_name='Имя')
    description = models.TextField(verbose_name='Описание', **NULLABLE)
    photo = models.ImageField(upload_to='blouses/', verbose_name='Превью', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.IntegerField(verbose_name='Цена')
    date_make = models.DateField(verbose_name='Дата создания')
    date_update = models.DateField(verbose_name='Дата изменения')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Кофта'
        verbose_name_plural = 'Кофты'


class Pants(models.Model):
    name = models.CharField(max_length=100, verbose_name='Имя')
    description = models.TextField(verbose_name='Описание', **NULLABLE)
    photo = models.ImageField(upload_to='pants/', verbose_name='Превью', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.IntegerField(verbose_name='Цена')
    date_make = models.DateField(verbose_name='Дата создания')
    date_update = models.DateField(verbose_name='Дата изменения')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Штаны'
        verbose_name_plural = 'Штаны'


class Socks(models.Model):
    name = models.CharField(max_length=100, verbose_name='Имя')
    description = models.TextField(verbose_name='Описание', **NULLABLE)
    photo = models.ImageField(upload_to='socks/', verbose_name='Превью', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.IntegerField(verbose_name='Цена')
    date_make = models.DateField(verbose_name='Дата создания')
    date_update = models.DateField(verbose_name='Дата изменения')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Носки'
        verbose_name_plural = 'Носки'


class Version(models.Model):
    product = models.ForeignKey(Sneakers, on_delete=models.CASCADE)
    version_number = models.CharField(max_length=100, verbose_name='номер версии')
    version_name = models.CharField(max_length=100, verbose_name='название версии')
    version_sign = models.CharField(max_length=100, verbose_name='признак версии')

    def __str__(self):
        return f'{self.version_number}'

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'

catalog/forms.py
from django import forms

from catalog.models import Sneakers


class SneakersForm(forms.ModelForm):
    class Meta:
        model = Sneakers
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']

        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        for item in forbidden_words:
            if item.lower() in cleaned_data.lower():
                raise forms.ValidationError(f'Нельзя использовать слово {item}')

        return cleaned_data

catalog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView

from catalog.forms import SneakersForm
from catalog.models import Category, Sneakers


def home(request):
    context = {
        'object_list': Category.objects.all()[:3],
        'title': 'Sneakers - Ваш стиль'
    }
    return render(request, 'catalog/home.html', context)


def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'{name} ({phone}) {message}')
    return render(request, 'catalog/contacts.html')


class CategoryListView(ListView):
    model = Category

    extra_context = {
        'title': 'Sneakers - Категории'
    }


class SneakersListView(ListView):
    model = Sneakers

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(category_id=Category.objects.filter(name='Кроссовки').get().id)
        return queryset

    extra_context = {
        'title': 'Sneakers - Кроссовки'
    }


class SneakersCreateView(CreateView):
    model = Sneakers
    form_class = SneakersForm
    success_url = reverse_lazy('catalog:categories')


class SneakersUpdateView(UpdateView):
    model = Sneakers
    form_class = SneakersForm
    success_url = reverse_lazy('catalog:categories')

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>
<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">Магазин на Ваш вкус</h4>
                    <p class="text-muted">Прогуляйтесь по страницам нашего магазина и выберете то, что Вам нравится</p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-white">Меню</h4>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'catalog:home' %}" class="text-white">Главная</a></li>
                        <li><a href="{% url 'catalog:categories' %}" class="text-white">Категории</a></li>
                        <li><a href="{% url 'catalog:sneakers' %}" class="text-white">Обувь</a></li>
                        <li><a href="#" class="text-white">Одежда</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Галерея</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

<main>

    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">{{ title }}</h1>
            </div>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">
            {% block content %}
            {% endblock %}


        </div>
    </div>

</main>

<footer class="text-muted py-5">
    <div class="container">
        <p class="float-end mb-1">
            <a href="#">2023</a>
        </p>
    </div>
</footer>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>


</body>
</html>

catalog/templates/catalog/categories.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for object in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    {% if object.name == "Кроссовки" %}
                        <img class="card-img-top"
                             src="/media/products/title_sneakers.jpg"
                             alt="Card image cap" width="100%" height="400">
                    {% elif object.name == "Одежда" %}
                        <img class="card-img-top"
                             src="/media/products/title_clothes.png"
                             alt="Card image cap" width="100%" height="400">
                    {% endif %}

                    <div class="card-body">
                        <p class="card-text">{{ object.name }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                {% if object.name == "Кроссовки" %}
                                    <a href="{% url 'catalog:sneakers' %}" type="button"
                                       class="btn btn-sm btn-outline-secondary">Смотреть товары</a>
                                {% elif object.name == "Одежда" %}
                                    <a href="#" type="button"
                                       class="btn btn-sm btn-outline-secondary">Смотреть товары</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for object in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    {% if object.name == "Кроссовки" %}
                        <img class="card-img-top"
                             src="/media/products/title_sneakers.jpg"
                             alt="Card image cap" width="100%" height="400">
                    {% elif object.name == "Одежда" %}
                        <img class="card-img-top"
                             src="/media/products/title_clothes.png"
                             alt="Card image cap" width="100%" height="400">
                    {% endif %}

                    <div class="card-body">
                        <p class="card-text">{{ object.name }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                {% if object.name == "Кроссовки" %}
                                    <a href="{% url 'catalog:sneakers' %}" type="button"
                                       class="btn btn-sm btn-outline-secondary">Смотреть товары</a>
                                {% elif object.name == "Одежда" %}
                                    <a href="#" type="button"
                                       class="btn btn-sm btn-outline-secondary">Смотреть товары</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Контакты</h1>
    </div>

    <div class="container">
        <div class="row text-start">
            <div class="col-lg-9 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <table class="table table-striped">
                            <tr>
                                <td class="w-25">Страна</td>
                                <td>USA</td>
                            </tr>
                            <tr>
                                <td class="w-25">ИНН</td>
                                <td>91-1144442</td>
                            </tr>
                            <tr>
                                <td class="w-25">Адрес</td>
                                <td>Redmond,WA,98052-6399</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" action="" class="form-floating">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="name">Имя</label>
                                <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                       required>
                            </div>
                            <div class="mb-3">
                                <label for="phone">Телефон</label>
                                <input type="text" name="phone" class="form-control" id="phone"
                                       placeholder="Контактный телефон" required>
                            </div>
                            <div class="mb-3">
                                <label for="message">Сообщение</label>
                                <textarea type="text" name="message" class="form-control" id="message"
                                          placeholder="Контактный телефон" required></textarea>
                            </div>
                        </form>
                        <input type="submit">
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/home.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Удобный сервис рассылок</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">$ 140</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- Неограниченная лицензия</li>
                        <li>- Поддержка</li>
                        <li>- Установка на сервер</li>
                        <li>- Получение обновлений</li>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load tags %}
{% block content %}
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col-12 mb-5">
            <a href="{% url 'catalog:sneakers_create' %}" class="btn btn-primary">Добавить товар</a>
        </div>
        {% for object in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <img class="card-img-top"
                         src="{{ object.photo|media_path }}"
                         alt="Card image cap" width="100%" height="600">

                    <div class="card-body">
                        <p class="card-text">{{ object.name }}</p>
                        <p class="card-text">{{ object.price }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="#" type="button" class="btn btn-sm btn-outline-secondary">На страницу
                                    товара</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/sneakers.html
{% extends 'catalog/base.html' %}
{% load tags %}
{% block content %}
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for object in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <img class="card-img-top"
                         src="{{ object.photo|media_path }}"
                         alt="Card image cap" width="100%" height="600">

                    <div class="card-body">
                        <p class="card-text">{{ object.name }}</p>
                        <p class="card-text">{{ object.price }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="#" type="button" class="btn btn-sm btn-outline-secondary">На страницу товара</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/sneakers_form.html
{% extends 'catalog/base.html' %}
{% block content %}
    <form method="post" class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    {% if object %}
                        Редактирование товара
                    {% else %}
                        Добавление товара
                    {% endif %}
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-outline-success">
                        {% if object %}
                            Сохранить
                        {% else %}
                            Добавить
                        {% endif %}
                    </button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

catalog/templates/catalog/sneakers_id.html
{% extends 'catalog/base.html' %}
{% load tags %}
{% block content %}
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
            <div class="card shadow-sm">
                <img class="card-img-top"
                     src="{{ object.photo|media_path }}"
                     alt="Card image cap" width="100%" height="600">

                <div class="card-body">
                    <p class="card-text">{{ object.name }}</p>
                    <p class="card-text">{{ object.description }}</p>
                    <p class="card-text">{{ object.price }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="#" type="button" class="btn btn-sm btn-outline-secondary">Купить</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/sneakers_list.html
{% extends 'catalog/base.html' %}
{% load tags %}
{% block content %}
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col-12 mb-5">
            <a href="{% url 'catalog:sneakers_create' %}" class="btn btn-primary">Добавить товар</a>
        </div>
        {% for object in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <img class="card-img-top"
                         src="{{ object.photo|media_path }}"
                         alt="Card image cap" width="100%" height="600">

                    <div class="card-body">
                        <p class="card-text">{{ object.name }}</p>
                        <p class="card-text">{{ object.price }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="#" type="button" class="btn btn-sm btn-outline-secondary">На страницу
                                    товара</a>
                                <a href="{% url 'catalog:update_sneakers' object.pk %}" type="button"
                                       class="btn btn-sm btn-outline-secondary">Изменить товар</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}